name: otpauth_migration
description: A Dart package to encode and decode the otpauth-migration URI format used to import into and export 2FA secrets from the Google Authenticator app.
version: 0.0.7
repository: https://github.com/johncallahan/otpauth_migration

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  protobuf: ^3.1.0
  fixnum: ^1.1.0

dev_dependencies:
  lints: ^2.3.0
  test: ^1.25.8

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
